apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-scheduler-policy
  namespace: kube-system
data:
  scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1
    kind: KubeSchedulerConfiguration
    profiles:
      - schedulerName: custom-scheduler
        plugins:
          score:
            enabled:
              - name: "NodeResourcesFit"
