apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-scheduler
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      component: custom-scheduler
  template:
    metadata:
      labels:
        component: custom-scheduler
    spec:
      serviceAccountName: custom-scheduler-sa
      containers:
        - name: kube-scheduler
          image: k8s.gcr.io/kube-scheduler:v1.25.0 
          command:
            - kube-scheduler
            - --config=/etc/kube-scheduler/scheduler-config.yaml
            - --leader-elect=true
          volumeMounts:
            - name: scheduler-policy
              mountPath: /etc/kube-scheduler/
              readOnly: true
      volumes:
        - name: scheduler-policy
          configMap:
            name: custom-scheduler-policy
